[build]
  command = "node generate-config.js"
  publish = "."

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "FIREBASE_API_KEY,FIREBASE_AUTH_DOMAIN,FIREBASE_DATABASE_URL,FIREBASE_PROJECT_ID,FIREBASE_STORAGE_BUCKET,FIREBASE_MESSAGING_SENDER_ID,FIREBASE_APP_ID,FIREBASE_MEASUREMENT_ID,FCM_SERVER_KEY,ADMIN_USERNAME,ADMIN_PASSWORD"

[functions]
  directory = "netlify/functions"
